### PR TITLE
Register Atakan

### PR DESCRIPTION
**Pull request by Atakan-Emre**

### CODE REVIEW

**Comment by mertssmnoglu** [comment]
Hi @Atakan-Emre 👋

Your page.json in your my-links repo should be in proper format.
"description" value should be in a single line. 
I created a pull request on your my-links repo. Please mention me to this pr after you changed it.

**Comment by Atakan-Emre** [comment]
Hi @mertssmnoglu 
I fixed the Page.json and push.
Thanks.

**Review by mertssmnoglu — APPROVED** [review]

**Comment by mertssmnoglu** [comment]
Approved and merged successfully.

https://links.dev/Atakan

**Comment by Atakan-Emre** [comment]
Thank you for everything.

**Pull request merged**
