### PR TITLE
Register “trevin”

### PR DESCRIPTION
**Pull request by tmchow**

### CODE REVIEW

**Comment by fatih-yavuz** [comment]
@tmchow your page.json seems invalid

**Comment by tmchow** [comment]
> @tmchow your page.json seems invalid

Any idea what is wrong? The json is valid: https://github.com/tmchow/my-links/blob/main/page.json

**Comment by fatih-yavuz** [comment]
I don't know what was the problem but CI passed now @tmchow, merging it

**Comment by tmchow** [comment]
> I don't know what was the problem but CI passed now @tmchow, merging it

The biggest change is I moved away from an empty string as a description value. You may want to check that out in case that’s a problem?

**Pull request merged**
