### PR TITLE
Register majmal

### PR DESCRIPTION
**Pull request by Maherukh**
Added myself in Please do merge!!!

### CODE REVIEW

**Comment by mertssmnoglu** [comment]
Hi @Maherukh you need to fill your page.json file with your own informations and links in your my-links repo.

**Comment by Maherukh** [comment]
Filled and updated both can you re-check

**Review by mertssmnoglu — APPROVED** [review]

**Comment by Maherukh** [comment]
Sorry to ping you again @mertssmnoglu just wanted to ask how long will it take for the changes to be reflected as I don't see my changes in the registry.yaml file also https://links.dev/majmal is not working yet

**Comment by mertssmnoglu** [comment]
> Sorry to ping you again @mertssmnoglu just wanted to ask how long will it take for the changes to be reflected as I don't see my changes in the registry.yaml file also https://links.dev/majmal is not working yet

I don't have merge access I just want to help you. When the maintainers get online they will review it.

**Comment by Maherukh** [comment]
Will it be by tomorrow? Also thanks for all the help ✌🏿

**Pull request merged**
