### PR TITLE
Update registry.yaml

### PR DESCRIPTION
**Pull request by ricardogouveia3**
Addsa HTML SP to create a links.dev for the meetup

### CODE REVIEW

**Review by esau-morais — COMMENTED** [review]
@ricardogouveia3, It seems like you didn't create or update your `page.json` file correctly, please take a look at the ["How to sign up" section](https://github.com/fatih-yavuz/links.dev#how-to-sign-up) for more details

**Comment by ricardogouveia3** [comment]
@esau-morais I've just forked the my links repo to the organization page, it contains the `page.json` file https://github.com/HTML-SP/my-links

**Comment by esau-morais** [comment]
> @esau-morais I've just forked the my links repo to the organization page, it contains the `page.json` file https://github.com/HTML-SP/my-links

If you take a look closely, you've forked but didn't meet the expectations described [here](https://github.com/fatih-yavuz/links.dev#required-pagejson-sections)

**Comment by ricardogouveia3** [comment]
@esau-morais oh ok, didn't know about this check, i've just edited the file with the meetup social links. Also, I've seen that I cannot register multiple usernames, but as I'm doing it as an meetup, I hope it is ok

**Comment by esau-morais** [comment]
> @esau-morais oh ok, didn't know about this check, i've just edited the file with the meetup social links. Also, I've seen that I cannot register multiple usernames, but as I'm doing it as an meetup, I hope it is ok

The CI still failing and now it is returning undefined because there's probably a syntax error on your `page.json`

**Pull request merged**
