### PR TITLE
Added me

### PR DESCRIPTION
**Pull request by necenzurat**

### CODE REVIEW

**Comment by mertssmnoglu** [comment]
Hi @necenzurat 
links.dev requires my-links repo in your profile and your own page.json Easily you can fork [this repo](https://github.com/fatih-yavuz/my-links) and update page.json

You can mention me when you're done.

**Comment by mertssmnoglu** [comment]
@necenzurat there is only one missing step to get your links.dev page. 

Updating the page.json in your my-links repo.

**Comment by necenzurat** [comment]
fixedz

**Comment by necenzurat** [comment]
Thanks


--
*Costin Moise* aka necenzurat
Dev-at-large 💻
Find me: +4 0726 459 188 <+4+0726.459.188> | Github
<https://github.com/necenzurat> | Linkedin
<http://www.linkedin.com/in/necenzurat>

**Pull request merged**
