### PR TITLE
add nuh

### PR DESCRIPTION
**Pull request by NuhYlmz**

### CODE REVIEW

**Comment by fatih-yavuz** [comment]
It seems like you don't have your own my-links repo and page.json. You can read README.md @NuhYlmz

**Comment by NuhYlmz** [comment]
> It seems like you don't have your own my-links repo and page.json. You can read README.md @NuhYlmz

@fatih-yavuz i already have it https://github.com/nuhylmz/my-links

**Comment by fatih-yavuz** [comment]
I see, it is because your branch name is master not main. Can you create a branch named main?

**Comment by NuhYlmz** [comment]
> eate a branch named main

yes that was the problem i changed it to main.

**Review by fatih-yavuz — APPROVED** [review]

**Pull request merged**
