### PR TITLE
Register nef

### PR DESCRIPTION
**Pull request by not-nef**

### CODE REVIEW

**Comment by mertssmnoglu** [comment]
Hi @not-nef  
Your [my-links](https://github.com/not-nef/my-links) repo should look like [this](https://github.com/fatih-yavuz/my-links).

Please check the [How to sign up](https://github.com/fatih-yavuz/links.dev/#how-to-sign-up) then update your my-links repo.
Please let us know when you done.

**Comment by mertssmnoglu** [comment]
Hello again @not-nef 

links.dev requires your personal my-links repo to create your page on `https://links.dev/{username}`. Please check [How to sign up](https://github.com/fatih-yavuz/links.dev/#how-to-sign-up) then create your own my-links repo. 

I would like to let you know, if you don't create the repo or don't get any action about it this pr may close due to timeout.

**Comment by not-nef** [comment]
oh im sorry, i seemed to have missed your first comment. yeah i will get to adding the page.json file tomorrow. Do you know if i can leave it empty for now and add my links later?

**Comment by mertssmnoglu** [comment]
> oh im sorry, i seemed to have missed your first comment. yeah i will get to adding the page.json file tomorrow. Do you know if i can leave it empty for now and add my links later?

Your `page.json` file need `image_url` key too. 
You can use your github avatar directly via `https://github.com/not-nef.png` or upload your image to trusted image provider(Or directly in your my-links repo).

**Comment by not-nef** [comment]
ok i added it, is everything alright now?

**Review by mertssmnoglu — APPROVED** [review]
Everything is allright. Approved.

**Pull request merged**
