### PR TITLE
Update registry.yaml

### PR DESCRIPTION
**Pull request by ILMpk**

### CODE REVIEW

**Comment by ILMpk** [comment]
updated page.json

**Comment by mertssmnoglu** [comment]
Hello @ILMpk you need to have a 'my-page' repository including page.json etc. 
Looks like you don't have a repository or you have but it's private.

Please follow the [How to sign up](https://github.com/fatih-yavuz/links.dev#how-to-sign-up) section.

**Comment by mertssmnoglu** [comment]
Could you please rename your repository to `my-links` @ILMpk

**Comment by ILMpk** [comment]
> Could you please rename your repository to `my-links` @ILMpk

I changed it to my-links now.

**Review by mertssmnoglu — APPROVED** [review]

**Comment by mertssmnoglu** [comment]
Ok, looks clear. Your changes will get online soon on https://links.dev/YOUR_USERNAME

Btw, please do not forget to change your links to https version. Thank you, have a great day.

**Pull request merged**
