### PR TITLE
Add stepersy

### PR DESCRIPTION
**Pull request by persanoadorno**
Please add stepersy, thanks!

### CODE REVIEW

**Comment by fatih-yavuz** [comment]
@persanoadorno this is an interesting PR. I would expect a single-line change 😄

**Comment by persanoadorno** [comment]
> 

Sorry, I don't understand😄. I did something wrong? I'm from phone, so it's a little difficult to use GitHub

**Comment by persanoadorno** [comment]
> > 
> 
> Sorry, I diti it wrong. I'm from phone so it's a little difficult to use GitHub 😄

**Comment by fatih-yavuz** [comment]
@persanoadorno your PR contains 79 file changes. Can you open a proper one with only registry.yaml? I am closing this one

**Pull request closed without merging**
